# -*- coding: utf-8 -*-
"""TASK2_Debugging.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1foElZCOZAppzfB-vFwZTEs6IR9hAoQGA
"""

import pandas as pd

df = pd.read_csv("/content/pima-indians-diabetes.csv", sep=",", header=None, comment='#')

df.columns = [
    "Pregnancies","Glucose","BloodPressure","SkinThickness",
    "Insulin","BMI","DiabetesPedigreeFunction","Age","Outcome"
]

df.head()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

# ❌ No random_state
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# ❌ Leakage
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = LogisticRegression()
model.fit(X_scaled[:len(y_train)], y_train)

y_pred = model.predict(X_scaled[len(y_train):])
print("Before Fix F1:", f1_score(y_test, y_pred))

import numpy as np
import random

SEED = 42
np.random.seed(SEED)
random.seed(SEED)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=SEED,
    stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LogisticRegression(max_iter=1000, random_state=SEED)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("After Fix F1:", f1_score(y_test, y_pred))

