# -*- coding: utf-8 -*-
"""TASK3_Performance_Improvement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10pa1Fcv2wslJWtZVC6wpOSXIXNbzKhe8
"""

import pandas as pd
import joblib

df = pd.read_csv("/content/pima-indians-diabetes.csv", sep=",", comment="#", header=None)

df.columns = [
    "Pregnancies","Glucose","BloodPressure","SkinThickness",
    "Insulin","BMI","DiabetesPedigreeFunction","Age","Outcome"
]

model = joblib.load("/content/diabetes_model.pkl")
scaler = joblib.load("/content/scaler.pkl")

from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
import numpy as np

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

# Recreate the engineered features that the scaler and model expect
X['bmi_squared'] = X['BMI']**2

# Handle potential division by zero for BMI by replacing 0 with NaN
X['temp_BMI'] = X['BMI'].replace(0, np.nan)
X['glucose_bmi_ratio'] = X['Glucose'] / X['temp_BMI']
X = X.drop('temp_BMI', axis=1) # Drop the temporary column

X['high_glucose'] = (X['Glucose'] > 140).astype(int) # Example threshold

# Example for age_bucket - adjust bins as per model's training
X['age_bucket'] = pd.cut(X['Age'], bins=[0, 30, 50, np.inf], labels=[0, 1, 2], right=False)
X['age_bucket'] = X['age_bucket'].astype(int)

# Fill any remaining NaN values that might have been introduced (e.g., from BMI=0) with the column mean
X = X.fillna(X.mean())

# Ensure feature order matches what the scaler was fitted on
# This assumes the scaler has a feature_names_in_ attribute, which is common in scikit-learn 1.0+
if hasattr(scaler, 'feature_names_in_'):
    X = X[scaler.feature_names_in_]
else:
    # Fallback if feature_names_in_ is not available. This might require
    # knowing the exact feature list and order from how the scaler was trained.
    # For this problem, assuming `feature_names_in_` is available is a reasonable first step.
    pass

X = scaler.transform(X)

y_pred_default = model.predict(X)

print("Baseline F1:", f1_score(y, y_pred_default))

import numpy as np

y_prob = model.predict_proba(X)[:, 1]

# threshold 0.3 instead of 0.5
y_pred_new = (y_prob >= 0.3).astype(int)

print("Improved F1:", f1_score(y, y_pred_new))

