# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/167Z4VsAW-QuvmfegLZFwGPM4wOZb7Chv
"""

!pip install streamlit
import streamlit as st
import joblib
import numpy as np

# Load model
# Make sure 'fraud_model.pkl' and 'scaler.pkl' are uploaded to your Colab environment.
# You can upload them using the file browser on the left sidebar in Colab.
try:
    model = joblib.load("fraud_model.pkl")
    scaler = joblib.load("scaler.pkl")
except FileNotFoundError:
    st.error("Error: Model files 'fraud_model.pkl' or 'scaler.pkl' not found. Please upload them to the Colab environment.")
    st.stop() # Stop Streamlit execution if files are missing

# Page config
st.set_page_config(
    page_title="Fraud Detection System",
    page_icon="🚨",
    layout="centered"
)

# Custom CSS
st.markdown("""
<style>
.main {
    background-color: #f7f9fc;
}
.card {
    padding: 20px;
    border-radius: 15px;
    background-color: white;
    box-shadow: 0px 4px 15px rgba(0,0,0,0.1);
    margin-bottom: 20px;
}
h1, h2 {
    text-align: center;
}
</style>
""", unsafe_allow_html=True)

# Title
st.markdown("<h1>🚨 Fraud Detection System</h1>", unsafe_allow_html=True)
st.markdown("<h4 style='text-align:center;'>Real-time Transaction Risk Analysis</h4>", unsafe_allow_html=True)
st.write("")

# Input Card
st.markdown("<div class='card'>", unsafe_allow_html=True)
st.subheader("🧾 Transaction Details")

amount = st.number_input("💰 Transaction Amount", min_value=1, step=10)
location_change = st.selectbox("📍 Location Changed?", ["No", "Yes"])
device_change = st.selectbox("📱 New Device Used?", ["No", "Yes"])
hour = st.slider("⏰ Transaction Hour", 0, 23)

st.markdown("</div>", unsafe_allow_html=True)

# Button
if st.button("🔍 Analyze Transaction"):
    loc = 1 if location_change == "Yes" else 0
    dev = 1 if device_change == "Yes" else 0

    data = np.array([[amount, loc, dev, hour]])
    data = scaler.transform(data)

    prob = model.predict_proba(data)[0][1]

    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.subheader("📊 Prediction Result")

    if prob > 0.5:
        st.error(f"🚨 **Fraud Detected**\n\nRisk Probability: **{prob:.2f}**")
    else:
        st.success(f"✅ **Legitimate Transaction**\n\nRisk Probability: **{prob:.2f}**")

    st.markdown("</div>", unsafe_allow_html=True)

# Footer
st.markdown("---")
st.markdown("<p style='text-align:center;'>Built for ML Engineering Practical Assessment</p>", unsafe_allow_html=True)

