# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/167Z4VsAW-QuvmfegLZFwGPM4wOZb7Chv
"""

import streamlit as st
import joblib
import numpy as np
import os

# Load model and scaler
# Make sure 'fraud_model.pkl' and 'scaler.pkl' are uploaded to your Colab environment.
# You can upload them using the file browser on the left sidebar in Colab.
model = joblib.load("fraud_model.pkl")
scaler = joblib.load("scaler.pkl")

# Page config
st.set_page_config(
    page_title="Fraud Detection System",
    page_icon="🚨",
    layout="centered"
)

# Custom CSS
st.markdown("""
<style>
body {
    background-color: #f7f9fc;
}
.card {
    background-color: white;
    padding: 20px;
    border-radius: 15px;
    box-shadow: 0px 4px 12px rgba(0,0,0,0.1);
    margin-bottom: 20px;
}
h1, h4 {
    text-align: center;
}
</style>
""", unsafe_allow_html=True)

# Title
st.markdown("<h1>🚨 Fraud Detection System</h1>", unsafe_allow_html=True)
st.markdown("<h4>Real-time Transaction Risk Analysis</h4>", unsafe_allow_html=True)

# Input Card
st.markdown("<div class='card'>", unsafe_allow_html=True)
st.subheader("🧾 Transaction Details")

amount = st.number_input("💰 Transaction Amount", min_value=1, step=10)
location_change = st.selectbox("📍 Location Changed?", ["No", "Yes"])
device_change = st.selectbox("📱 New Device Used?", ["No", "Yes"])
hour = st.slider("⏰ Transaction Hour", 0, 23)

st.markdown("</div>", unsafe_allow_html=True)

# Prediction
if st.button("🔍 Analyze Transaction"):
    loc = 1 if location_change == "Yes" else 0
    dev = 1 if device_change == "Yes" else 0

    input_data = np.array([[amount, loc, dev, hour]])
    input_scaled = scaler.transform(input_data)

    prob = model.predict_proba(input_scaled)[0][1]

    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.subheader("📊 Result")

    if prob >= 0.5:
        st.error(f"🚨 **Fraud Detected**\n\nRisk Probability: **{prob:.2f}**")
    else:
        st.success(f"✅ **Legitimate Transaction**\n\nRisk Probability: **{prob:.2f}**")

    st.markdown("</div>", unsafe_allow_html=True)

# Footer
st.markdown("---")
st.markdown("<p style='text-align:center;'>ML Engineering Practical Assessment</p>", unsafe_allow_html=True)

